import Head from "next/head";
import MainLayout from "../components/layouts/MainLayout";

export default function Home() {
  return (
    <MainLayout>
      <Head>
        <title>flexo-static</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* all the components come here */}
      <header>This is header 2</header>
      <header>This is header 3</header>
      <header>This is header 4</header>
    </MainLayout>
  );
}
